### ISSUE TITLE
读取graph_opt.pb出错

### ISSUE THREAD

**Issue by ghost** [TianzhongSong/Real-Time-Action-Recognition#19]
f=tf.gfile.GFile(graph_path, 'rb') #graph_path 我已经修改为我本机上该文件的路径
f.read()

---------------------------------------------------
f= tf.gfile.GFile(graph_path, 'rb')
f.read()
Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2927, in run_code
    self.showtraceback(running_compiled_code=True)

  File "D:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1833, in showtraceback
    self._showtraceback(etype, value, stb)

  File "D:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 558, in _showtraceback
    dh.parent_header, ident=topic)

  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\session.py", line 737, in send
    to_send = self.serialize(msg, ident)

  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\session.py", line 625, in serialize
    content = self.pack(content)

  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,

  File "D:\ProgramData\Anaconda3\lib\site-packages\zmq\utils\jsonapi.py", line 43, in dumps
    s = s.encode('utf8')

UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd5' in position 1402: surrogates not allowed

**Comment by ghost** [comment]
搞定了，路径中不能有中文
