### ISSUE TITLE
Error while compilation

### ISSUE THREAD

**Issue by hemanthkumar3111** [TianzhongSong/Real-Time-Action-Recognition#6]
Hi Without modifying your code I just compiled it but getting this error.
Any help will be appreciated.(tensorflow_p36) ubuntu@ip-172-31-62-23:~/Real-Time-Action-Recognition$ python run.py
/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
 from ._conv import register_converters as _register_converters
Traceback (most recent call last):
 File "run.py", line 5, in <module>
   from utils.sort import Sort
 File "/home/ubuntu/Real-Time-Action-Recognition/utils/__init__.py", line 1, in <module>
   from . import processing
ImportError: cannot import name 'processing'

**Comment by TianzhongSong** [comment]
@hemanthkumar3111  Sorry, this is a bug of old version, I have modified this bug by deleting the contents of [utils/__init__.py](https://github.com/TianzhongSong/Real-Time-Action-Recognition/blob/master/utils/__init__.py)
